# Arquivo IaC- inafraestrutura descrita em código, e o Kubernetes irá montar essa estrutura
# define o estado desejado da sua aplicação dentro do Kubernetes

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-js
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-node
  template:
    metadata:
      labels:
        app: web-node
    spec:
      containers:
        - name: node-app
          image: nginx:alpine
          ports:
            - containerPort: 80
